### PR TITLE
Update to work with Django 4.0.

### PR DESCRIPTION
**Pull request by ntoll**
Based upon / replaces / fixes PR #201.

**NOTE** I made these changes very quickly and have not (yet) been able to run the test suite.

@grantmcconnaughey **please check before merging**.

I'm happy (and responsive) to change/squash anything you need to get this into a release.

Finally, thank you for your work maintaining this project. :heart: :rocket: :snake:

### CODE REVIEW

**Comment by pulse-mind** [comment]
It is working on my project.
@ntoll thank you

**Comment by Ali-Aref** [comment]
Waited long time to be merged but now..
uninstalled **django-avatar** and
install your **repo** as `pip install git+https://github.com/ntoll/django-avatar` and it's working well :100: .

**Comment by pulse-mind** [comment]
Great thank you. 

Would you like to publish a news release (3.2.0...)  in order to use it thru pypi?

**Comment by ntoll** [comment]
@pulse-mind the only person who could do that (cut a new release) is @grantmcconnaughey - but please remember everyone around here is a volunteer and he'll have time constraints and so on.

In the meantime, using the direct link to the GitHub repository will work as a temporary solution (which is what I'm also doing now that my app is updated to Django 4). :+1:

**Comment by johanneswilm** [comment]
Ping @grantmcconnaughey . Could you either merge one of these or hand off maintenance to someone else?

**Pull request merged**
