### PR TITLE
Make Django 3.2 and 4.0 compatible

### PR DESCRIPTION
**Pull request by johanneswilm**
This includes the three different PRs for Django 3.2 and 4.0 compatibility.

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @rsp2k @ntoll @luigi370 @alexbieg-skilljar @pulse-mind,

it looks like @grantmcconnaughey has given up on this package. Maybe it's time to fork it and add another package to pypi? Any of you up for collaborating on that?

**Comment by johanneswilm** [comment]
@pulse-mind thanks! That works, but it doesn't work quite the same way that having a pypi package would - for example when it comes to updating the package. Also, it depends on ntoll keeping that repository and not adding commits that break your setup forever. That's why a pypi package would be preferable.  
As long as it is updating to newer django versions, I don't care who publishes it there. @ntoll would you be willing to maintain a fork with packages on pypi?

**Comment by grantmcconnaughey** [comment]
I'll get it moved to jazzband. At a conference this week so it'll have to be after that.

**Comment by johanneswilm** [comment]
@grantmcconnaughey great. So Monday the 16th or around there?

**Comment by grantmcconnaughey** [comment]
No, I'll be on vacation then. I can't provide a specific date on when I'll get to it.

**Comment by johanneswilm** [comment]
Ok, so conference this week and then vacation next week? Maybe the easiest is if we just create a fork for now and publish to pypi and then we can take it down again when you get to moving to jazzband or merging one of the PRs and publishing a new release. What do you think>

**Comment by johanneswilm** [comment]
@grantmcconnaughey thanks! And I agree, that will probably already work for a lot of users. Others will have ti wait for the pypi release.

**Comment by johanneswilm** [comment]
Hey @grantmcconnaughey - it's been another 2 months. Any chance that it can be transferred to jazzband and/or we can get a release on pypi, @grantmcconnaughey ?

**Pull request merged**
