### PR TITLE
Transpose thumbnails based on EXIF orientation

### PR DESCRIPTION
**Pull request by fstehle**
Transpose the original image before resizing based on EXIF orientation
information to display image in the correct orientation. If someone
uploads an image from an iPhone (for example) the image is currently
often rendered in the wrong orientation.

based on https://github.com/grantmcconnaughey/django-avatar/pull/83

### CODE REVIEW

**Comment by fstehle** [comment]
PTAL @grantmcconnaughey

**Comment by fstehle** [comment]
Hey @grantmcconnaughey, could you please have a look at this PR?
Is there anything missing in order to get this merged?
Thanks a lot

**Comment by fstehle** [comment]
Hey @grantmcconnaughey, anything we can do in order to get this PR merged?

**Comment by grantmcconnaughey** [comment]
Hey @fcurella, I apologize for the delay. I'm working on django-avatar 5.0 right now and I am planning on making this PR a part of that.

Thanks!

**Pull request merged**
