### PR TITLE
Prevented creation of the new migrations with non-default DEFAULT_FILE_STORAGE.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by grantmcconnaughey** [comment]
Hey @sir-sigurd, this looks good. Since this changes an existing migration, I'm wondering if this will affect django-avatar users that have already run this migration. What do you think?

**Comment by sir-sigurd** [comment]
@grantmcconnaughey, I reworked this PR:

1. Added migration instead of modifying the existing one. Though it could be not needed really, it's more predictable.
2. AVATAR_STORAGE setting doesn't lead to creation of new migrations.

**Comment by lewellent** [comment]
Hey @grantmcconnaughey, thanks for your work on this project.  Any chance we could get this specific issue accepted and merged?  We've been plagued with quite a few rogue migrations on one of our projects due to this issue.

**Comment by grantmcconnaughey** [comment]
Sure thing. I'll try to get to it within the next couple of days.

**Comment by grantmcconnaughey** [comment]
I didn't have access to change @sir-sigurd's fork, so I made this change in [this commit](https://github.com/grantmcconnaughey/django-avatar/commit/f8716937b0986b087ec3bb2220108f496a908538).

**Comment by grantmcconnaughey** [comment]
@lewellent @sir-sigurd This fix has been [released to PyPI](https://pypi.python.org/pypi/django-avatar/4.0.1)! Thanks for making the PR.

**Pull request closed without merging**
