### PR TITLE
Fixes the Django 3.0 `six` issue

### PR DESCRIPTION
**Pull request by bastbnl**
Not sure if this is all for Django 3

### CODE REVIEW

**Comment by smallnine9** [comment]
still error：ModuleNotFoundError: No module named 'six'

**Comment by Daveson217** [comment]
The error is still occuring:    ModuleNotFoundError: No module named 'six', using version 5.0

**Comment by Daveson217** [comment]
I was able to solve it by installing [six](https://github.com/benjaminp/six), and then changing line 13 in avatar/utils.py to
`import six`

**Comment by smallnine9** [comment]
thanks,I will try it

**Pull request merged**
